# Generated by Django 4.1.1 on 2022-10-17 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SocialPlatform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(default=0, max_length=20)),
            ],
            options={"db_table": "social_platforms",},
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nickname", models.CharField(max_length=100, null=True)),
                ("is_valid", models.BooleanField(blank=True, default=True)),
                (
                    "social_login_id",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                ("refresh_token", models.CharField(max_length=500, null=True)),
                ("email", models.CharField(max_length=100, null=True)),
                (
                    "social",
                    models.ForeignKey(
                        blank=True,
                        default=1,
                        max_length=20,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.socialplatform",
                    ),
                ),
            ],
            options={"db_table": "users",},
        ),
    ]
