# Generated by Django 4.1.1 on 2022-10-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="review", name="updated_at",),
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
